export const Users = [
  {
    id: 1,
    profilePicture: "https://th.bing.com/th/id/OIP.ipw91480g6vPil4FHsUzpwHaEK?w=309&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    username: "Boyan Iliev",
  },
  {
    id: 2,
    profilePicture: "https://th.bing.com/th/id/OIP.au676JN4jHXuG7tXEXVXuAHaD-?w=289&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    username: "Kaloyan Kaloyan",
  },
  {
    id: 3,
    profilePicture: "https://th.bing.com/th/id/OIP.B2Elkxhj2eODYCLH8V8msQHaJ4?w=182&h=243&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    username: "Krasimir Krasimir",
  },
  {
    id: 4,
    profilePicture: "https://th.bing.com/th/id/OIP.QTr9mgz1n9L5wQY5e9ImOwHaH1?w=182&h=192&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    username: "Tosho Kukata Hawks",
  },
  {
    id: 5,
    profilePicture: "https://th.bing.com/th/id/OIP.QTr9mgz1n9L5wQY5e9ImOwHaH1?w=182&h=192&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    username: "Ivan Iordanov",
  },
  {
    id: 6,
    profilePicture: "https://th.bing.com/th/id/OIP.QTr9mgz1n9L5wQY5e9ImOwHaH1?w=182&h=192&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    username: "Bebeshon Beauchamp",
  },
  {
    id: 7,
    profilePicture: "https://th.bing.com/th/id/OIP.QTr9mgz1n9L5wQY5e9ImOwHaH1?w=182&h=192&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    username: "Travis Scott",
  },
  {
    id: 8,
    profilePicture: "https://th.bing.com/th/id/OIP.QTr9mgz1n9L5wQY5e9ImOwHaH1?w=182&h=192&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    username: "Ivan Thomas",
  },
  {
    id: 9,
    profilePicture: "https://th.bing.com/th/id/OIP.QTr9mgz1n9L5wQY5e9ImOwHaH1?w=182&h=192&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    username: "Call of Duty",
  },
  {
    id: 10,
    profilePicture: "https://th.bing.com/th/id/OIP.QTr9mgz1n9L5wQY5e9ImOwHaH1?w=182&h=192&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    username: "Putin Ukraine",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
